version: '3.8'
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html:cached  # Ensure this is correctly set
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpass
      MYSQL_DATABASE: lesson_db
    ports:
      - "8080:80"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lesson_db
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
