version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=student
      - MYSQL_PASSWORD=studentpass
      - MYSQL_DATABASE=studentdb
    network_mode: service:db
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=studentdb
      - MYSQL_USER=student
      - MYSQL_PASSWORD=studentpass

volumes:
  mysql-data:
