version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/php:0-8.1
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=student
      - MYSQL_PASSWORD=studentpass
      - MYSQL_DATABASE=studentdb

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=studentdb
      - MYSQL_USER=student
      - MYSQL_PASSWORD=studentpass
    cap_add:
      - SYS_NICE

volumes:
  mysql-data: